name: Added Manually 

on: 
  workflow_dispatch:

env:
  AWS_REGION: "ap-south-1"

permissions:
  id-token: write
  contents: read
  
jobs:
  verify-secrets-access:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        # The output will be masked
        echo ${{ secrets.SAME_SECRET_MANUALLY_ADDED }} 
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.SAME_SECRET_MANUALLY_ADDED }}
        aws-region: ${{ env.AWS_REGION }}
